import WhiskyCardProps from "@/types/product/whisky";

export const WhiskyData: WhiskyCardProps[] = [
  {
    slug: "distillerie-warenghem-armorik-double-maturation",
    brand: "Distillerie Warenghem",
    title: "ARMORIK DOUBLE maturation",
    note: "91",
    thumbId: "60b689c4-c3d4-4042-815d-cc934fbc3fc0",
    featured: false,
    originCountry: "France",
    region: "Bretagne",
    classification: "Single Malt Whisky",
    alcoholVolume: "46%",
    priceRange: "40€ à 60€",
  },
  {
    slug: "distillerie-la-mine-dor-galaad-roi-de-coeur",
    brand: "Distillerie La Mine d'Or",
    title: "GALAAD \"ROI DE COEUR\"",
    note: "91",
    thumbId: "839cf202-45f1-47af-9d1d-b121377e3280",
    featured: false,
    originCountry: "France",
    region: "Bretagne",
    classification: "Single Malt Whisky",
    alcoholVolume: "46.2%",
    priceRange: "100€ à 200€",
  },
  {
    slug: "celtic-whisky-distillerie-kornog-saint-ivy",
    brand: "Celtic Whisky Distillerie",
    title: "KORNOG SAINT IVY",
    note: "90",
    thumbId: "3154ad95-fd27-41eb-8520-b82974d8e8ca",
    featured: false,
    originCountry: "France",
    region: "Bretagne",
    classification: "Single Malt Whisky",
    rawMaterial: "Orge Maltée",
    alcoholVolume: "57.7%",
    priceRange: "100€ à 200€",
  },
];
