import WineCardProps from "@/types/product/wine";

export const WineData: WineCardProps[] = [
  {
    slug: "domaine-de-chatenoy-clos-des-treilles",
    domainSlug: "domaine-de-chatenoy",
    brand: "Domaine de Châtenoy",
    title: "Clos des Treilles",
    note: "94",
    thumbId: "b974cfb4-6a7f-48eb-ae8c-86b184704a09",
    featured: false,
    vintage: "2022",
    appellation: ["Loire", "Menetou-Salon"],
    colorCode: "Blanc",
    varieties: { "Sauvignon blanc": 100 },
    priceRange: "15€ à 30€",
  },
  {
    slug: "yann-chave-le-rouvre",
    domainSlug: "yann-chave",
    brand: "Yann Chave",
    title: "Le Rouvre",
    note: "94",
    thumbId: "68848fff-3369-4958-8b00-21f3866fa065",
    featured: false,
    vintage: "2022",
    appellation: ["Rhône", "Crozes-Hermitage"],
    colorCode: "Rouge",
    varieties: { Syrah: 100 },
    priceRange: "30€ à 50€",
  },
  {
    slug: "cave-yves-cuilleron-les-rousses",
    domainSlug: "cave-yves-cuilleron",
    brand: "Cave Yves Cuilleron",
    title: "Les Rousses",
    note: "94",
    thumbId: "e1270985-3a3c-4769-9c4f-8badda31b929",
    featured: false,
    vintage: "2023",
    appellation: ["Rhône", "Crozes-Hermitage"],
    colorCode: "Rosé",
    varieties: { "Chardonnay": 100 },
    priceRange: "30€ à 50€",
  },
];
